import {selectReviewState} from './tools/qa-review-tools.mjs';
import { test, expect } from "@playwright/test";
import { readFile } from "node:fs/promises";
test.use({ channel: "chrome" });
const base = process.env.YPBI_BASE_URL ?? "http://127.0.0.1:5197";
const href = `${base}/dashboards/public?design=dashboard-center&board=5.5`;
async function expectOverallNavigation(navigation) {
  await expect(navigation.getByRole("radiogroup", { name: "展示方式", exact: true })).toHaveCount(0);
  for (const name of ["客户端分组", "人群分组"]) await expect(navigation.getByRole("group", { name, exact: true })).toHaveCount(0);
  await expect(navigation.getByRole("table", { name: "导航使用二维交叉表", exact: true })).toHaveCount(0);
  await expect(navigation.getByRole("button", { name: "恢复总体", exact: true })).toHaveCount(0);
  await expect(navigation).not.toContainText(/Android|iOS|新用户|老用户|未识别客户端/);
  await expect(navigation.locator('[aria-label="所选导航周期摘要"]')).toContainText("整体");
}
function expectOverallNavigationExport(raw) {
  for (const text of ["05_全局导航", "06_导航逐日", "整体", "demo-global-tab-5", "对比期"]) expect(raw).toContain(text);
  for (const text of ["07_导航结构", "分组", "Android", "iOS", "新用户", "老用户", "未识别客户端"]) expect(raw).not.toContain(text);
}
test.afterEach(async ({ page }, info) => { if (info.status !== info.expectedStatus) await page.screenshot({ path: "/private/tmp/ypbi-function-failure.png", fullPage: true }); });
test("功能范围窄屏边界", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 1000 });
  const view = { range: { start: "2026-09-03", end: "2026-09-03" }, compared: false, mixed: false, selected: ["video_home"], days: 30, dimension: "平台" };
  await page.goto(`${href}&view=${encodeURIComponent(JSON.stringify(view))}`);
  await expect(page.getByRole("table", { name: "功能使用二维交叉表", exact: true })).toBeVisible();
  const width = await page.evaluate(() => document.documentElement.scrollWidth);
  expect(width).toBeLessThanOrEqual(390);
});
test("全功能比较、主动选择五项、图例翻页、单功能交叉与单一关闭", async ({ page }) => {
  await page.setViewportSize({ width: 1280, height: 1000 }); await page.goto(href+"&view="+encodeURIComponent(JSON.stringify({range:{start:"2026-09-02",end:"2026-09-08"},compared:true,mixed:false,selected:[],days:7,dimension:"平台"})));
  await expect(page.getByRole("heading", { name: "功能使用概览", exact: true })).toBeVisible();
  await expect(page.getByText("选择要查看的功能", { exact: true })).toBeVisible();
  const overview = page.getByRole("article", { name: "各功能使用概览", exact: true });
  const dialog = overview; await expect(dialog.locator("tbody tr")).toHaveCount(50);
  await expect(overview.getByRole("columnheader", { name: "使用用户数", exact: true })).toBeVisible();
  await expect(overview.getByRole("columnheader", { name: "同范围活跃用户数", exact: true })).toBeVisible();
  await expect(overview.getByRole("img", { name: "全部功能渗透率横向比较" })).toHaveCount(0);
  await dialog.getByRole("textbox", { name: "搜索功能", exact: true }).fill("video_home");
  await expect(dialog.locator("tbody tr")).toHaveCount(1);
  await dialog.getByRole("button", { name: "导出功能使用结果", exact: true }).click();
  const exporting = page.getByRole("dialog", { name: "导出功能使用结果", exact: true });
  await expect(exporting.getByRole("button", { name: /^关闭/ })).toHaveCount(1);
  const downloading = page.waitForEvent("download");
  await exporting.getByRole("button", { name: "下载演示 XLSX", exact: true }).click();
  const download = await downloading, raw = (await readFile(await download.path())).toString();
  expect(raw).toContain("01_功能概览"); expect(raw).toContain("演示");
  expect(raw).toContain("video_home"); expect(raw).toContain("physical_goods_detail");
  await dialog.getByRole("textbox", { name: "搜索功能", exact: true }).fill("");
  await page.keyboard.press("Escape");
  await page.getByText("选择趋势功能（0/5）", { exact: true }).click();
  const choices = page.locator(".function-preview__choices input");
  for (let i=0; i<5; i++) await choices.nth(i).check();
  await expect(choices.nth(5)).toBeDisabled();
  await expect(page.getByRole("img", { name: "所选功能渗透率多系列趋势" })).toBeVisible();
  await expect(page.getByRole("article", { name: "各功能使用概览" })).toContainText("50 个页面");
  for (let i=4; i>0; i--) await choices.nth(i).uncheck();
  await expect(page.getByRole("region", { name: "单功能分析范围", exact: true })).toBeVisible();
  await expect(page.getByRole("article", { name: "所选功能详情与趋势", exact: true }).locator(".topic-preview__group-summary section")).toHaveCount(4);
  await expect(page.getByRole("table", { name: "功能使用二维交叉表" }).locator("tbody tr")).toHaveCount(5);
  await page.reload(); await expect(page.getByRole("table", { name: "功能使用二维交叉表" })).toBeVisible();
  await selectReviewState(page, '组合异常态');
  await expect(page.getByRole("table", { name: "功能使用二维交叉表" }).getByRole("button").filter({ hasText: "0.00%" })).toHaveCount(12);
  await expect(page.getByRole("img", { name: /功能渗透率日趋势/ })).toBeVisible();
  await expect(overview).toContainText("未启用"); await expect(overview).toContainText("无记录");
  await overview.getByRole("button", { name: "重试", exact: true }).click(); await expect(overview).not.toContainText("查询失败");
});
test("单日、整月、366日与手机完整表格均实际渲染", async ({ page }) => {
  test.setTimeout(180000);
  const errors=[]; page.on("pageerror", e=>errors.push(e.message));
  for (const width of [1280,1024,390]) for (const range of [{ start:"2026-09-03",end:"2026-09-03" },{ start:"2026-08-01",end:"2026-08-31" },{ start:"2025-09-08",end:"2026-09-08" }]) {
    await page.setViewportSize({ width, height:900 });
    const view={range,compared:false,mixed:false,selected:["video_home"],days:30,dimension:"平台"};
    await page.goto(`${href}&view=${encodeURIComponent(JSON.stringify(view))}`);
    await expect(page.getByRole("article",{name:"各功能使用概览"})).toContainText(range.start, { timeout: 20_000 });
    const title = page.getByRole("heading", { name: "功能使用概览", exact: true });
    expect(await title.evaluate(el => el.getBoundingClientRect().height)).toBeLessThan(35);
    expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);
    if(width===390) { await expect(page.getByRole("table",{name:"全部功能使用结果"})).toBeVisible(); await expect(page.getByRole("table",{name:"全部功能使用结果"}).locator("tbody tr")).toHaveCount(50); }
    await page.screenshot({path:`/private/tmp/ypbi-function-${width}.png`});
  }
  expect(errors).toEqual([]);
});

test("导航始终使用整体，旧链接保留Tab指标且刷新历史与导出一致", async ({ page }) => {
  await page.setViewportSize({ width: 1280, height: 1000 });
  const view = { range: { start: "2026-09-02", end: "2026-09-08" }, compared: true, mixed: false, selected: [], days: 7, dimension: "平台", navigation: { selected: "demo-global-tab-1", measure: "penetration", scope: { client: "ios", audience: "new" } } };
  await page.goto(`${href}&view=${encodeURIComponent(JSON.stringify(view))}`);
  const navigation = page.getByRole("article", { name: "全局导航", exact: true });
  await expectOverallNavigation(navigation);
  await expect(navigation.getByRole("button", { name: "演示导航 01", exact: true })).toHaveAttribute("aria-pressed", "true");
  await expect(navigation.getByRole("radio", { name: "渗透率", exact: true })).toBeChecked();
  const readableSummary = navigation.locator('[aria-label="所选导航周期摘要"]');
  await expect(readableSummary).toContainText("同范围活跃用户数");
  const table = navigation.getByRole("table", { name: "全局导航使用结果" });
  const values = await table.locator("tbody tr").first().locator("td").allTextContents();
  const num = text => Number(text.replaceAll(",", "").replace("%", ""));
  expect(num(values[3])).toBeCloseTo(num(values[0]) / num(values[2]) * 100, 2);
  expect(num(await readableSummary.locator(".metric-summary__number").innerText())).toBeCloseTo(num(values[3]), 2);
  await navigation.getByRole("radio", { name: "使用者人均点击次数", exact: true }).click();
  await expect(readableSummary).toContainText("点击次数"); await expect(readableSummary).toContainText("点击用户数");
  expect(num((await readableSummary.locator(".metric-summary__number strong").innerText()))).toBeCloseTo(num(values[1]) / num(values[0]), 2);
  expect(JSON.parse(new URL(page.url()).searchParams.get("view")).navigation).toEqual({ selected: "demo-global-tab-1", measure: "frequency" });
  await page.reload(); await expectOverallNavigation(navigation);
  await expect(navigation.getByRole("radio", { name: "使用者人均点击次数", exact: true })).toBeChecked();
  await expect(navigation.getByRole("heading", { name: "演示导航 01 · 使用趋势", exact: true })).toBeVisible();
  await navigation.getByRole("button", { name: "演示导航 03", exact: true }).click();
  await page.goBack();
  await expect(navigation.getByRole("button", { name: "演示导航 01", exact: true })).toHaveAttribute("aria-pressed", "true");
  await expect(navigation.getByRole("radio", { name: "使用者人均点击次数", exact: true })).toBeChecked();
  await expectOverallNavigation(navigation);
  await page.goForward();
  await expect(navigation.getByRole("button", { name: "演示导航 03", exact: true })).toHaveAttribute("aria-pressed", "true");
  await expect(navigation.getByRole("radio", { name: "使用者人均点击次数", exact: true })).toBeChecked();
  await expectOverallNavigation(navigation);
  await navigation.getByRole("button", { name: "演示导航 01", exact: true }).click();
  await navigation.getByRole("radio", { name: "渗透率", exact: true }).click();
  expect(num(await readableSummary.locator(".metric-summary__number").innerText())).toBe(num(values[3]));
  await navigation.getByRole("button", { name: "导出全局导航", exact: true }).click();
  const downloading = page.waitForEvent("download");
  await page.getByRole("dialog", { name: "导出全局导航", exact: true }).getByRole("button", { name: "下载演示 XLSX", exact: true }).click();
  const raw = (await readFile(await (await downloading).path())).toString();
  expectOverallNavigationExport(raw);
  for (const text of ["当前范围", "2026-08-26", "2026-09-08"]) expect(raw).toContain(text);
  const legacyDimension = { ...view, navigation: { selected: "demo-global-tab-3", measure: "frequency", dimension: "userType" } };
  await page.goto(`${href}&view=${encodeURIComponent(JSON.stringify(legacyDimension))}`);
  await expectOverallNavigation(navigation);
  await expect(navigation.getByRole("button", { name: "演示导航 03", exact: true })).toHaveAttribute("aria-pressed", "true");
  await expect(navigation.getByRole("radio", { name: "使用者人均点击次数", exact: true })).toBeChecked();
  await page.reload(); await expectOverallNavigation(navigation);
  await expect(navigation.getByRole("button", { name: "演示导航 03", exact: true })).toHaveAttribute("aria-pressed", "true");
  await expect(navigation.getByRole("radio", { name: "使用者人均点击次数", exact: true })).toBeChecked();
});

test("功能局部范围联动不改50项总体，基数与导出完整，旧获客结构保留", async ({ page }) => {
  await page.setViewportSize({ width: 1280, height: 1000 });
  const view = { range: { start: "2026-09-02", end: "2026-09-08" }, compared: true, mixed: false, selected: ["video_home"], days: 7, dimension: "获客类型" };
  await page.goto(`${href}&view=${encodeURIComponent(JSON.stringify(view))}`);
  const overview = page.getByRole("article", { name: "各功能使用概览", exact: true });
  const overviewValues = await overview.getByRole("table").innerText();
  await expect(overview).toContainText("总体范围");
  const cross = page.getByRole("table", { name: "功能使用二维交叉表", exact: true });
  await cross.getByRole("button", { name: /^iOS · 老用户/ }).click();
  const detail = page.getByRole("article", { name: "所选功能详情与趋势", exact: true });
  await expect(detail).toContainText("iOS · 老用户"); await expect(detail).toContainText("同范围活跃用户数");
  expect(await overview.getByRole("table").innerText()).toBe(overviewValues);
  const value = await cross.getByRole("button", { name: /^iOS · 老用户/ }).textContent();
  const rate = value.split(" · ").at(-1).replace("%", "").trim();
  await expect(detail.locator(".metric-summary__number strong")).toHaveText(rate);
  await expect(page.getByRole("table", { name: "功能获客类型结构", exact: true })).toBeVisible();
  await page.reload(); await expect(detail).toContainText("iOS · 老用户");
  await page.getByRole("button", { name: "导出功能结构", exact: true }).click();
  const downloading = page.waitForEvent("download"); await page.getByRole("dialog", { name: "导出功能结构", exact: true }).getByRole("button", { name: "下载演示 XLSX", exact: true }).click();
  const raw = (await readFile(await (await downloading).path())).toString();
  for (const text of ["功能局部范围", "iOS · 老用户", "总体 · 总体", "Android · 新用户", "获客类型 · 未归因", "对比期"]) expect(raw).toContain(text);
  await detail.getByRole("button", { name: "恢复总体", exact: true }).click();
  await expect(detail).toContainText("总体 · 总体");
});

test("导航长日期摘要不随缩放改变，零与部分状态及三档联动实图", async ({ page }) => {
  test.setTimeout(90000);
  const errors = []; page.on("pageerror", error => errors.push(error.message));
  const view = { range: { start: "2026-08-01", end: "2026-09-08" }, compared: true, mixed: false, selected: ["video_home"], days: 30, dimension: "平台", navigation: { selected: "demo-global-tab-1", measure: "penetration" } };
  for (const width of [1280, 1024, 390]) {
    await page.setViewportSize({ width, height: 1000 }); await page.goto(`${href}&view=${encodeURIComponent(JSON.stringify(view))}`);
    const navigation = page.getByRole("article", { name: "全局导航", exact: true });
    await expectOverallNavigation(navigation);
    const summary = navigation.locator('[aria-label="所选导航周期摘要"]');
    const original = await summary.innerText();
    const sliders = navigation.getByRole("slider");
    if (await sliders.count()) { await sliders.first().focus(); await page.keyboard.press("ArrowRight"); expect(await summary.innerText()).toBe(original); }
    const overallRate = await navigation.getByRole("table", { name: "全局导航使用结果", exact: true }).locator("tbody tr").first().locator("td").nth(3).innerText();
    await expect(summary.locator(".metric-summary__number strong")).toHaveText(overallRate.replace("%", ""));
    await summary.scrollIntoViewIfNeeded();
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);
    await page.screenshot({ path: `/private/tmp/ypbi-navigation-overall-${width}.png` });
    const controls = page.getByRole("region", { name: "单功能分析范围", exact: true });
    await controls.getByRole("group", { name: "客户端分组", exact: true }).getByRole("button", { name: "iOS", exact: true }).click();
    expect(await summary.innerText()).toBe(original);
    await expectOverallNavigation(navigation);
    await controls.scrollIntoViewIfNeeded(); await page.screenshot({ path: `/private/tmp/ypbi-228-function-${width}.png` });
  }
  await selectReviewState(page, "组合异常态");
  const navigation = page.getByRole("article", { name: "全局导航", exact: true });
  await navigation.getByRole("button", { name: "演示导航 01", exact: true }).click();
  await navigation.getByRole("radio", { name: "使用者人均点击次数", exact: true }).click();
  await expect(navigation.locator('[aria-label="所选导航周期摘要"]')).toContainText("点击用户基数为0");
  await expectOverallNavigation(navigation);
  await navigation.getByRole("radio", { name: "渗透率", exact: true }).click();
  await expect(navigation.locator('[aria-label="所选导航周期摘要"]')).toContainText("整体");
  await expect(navigation.locator('[aria-label="所选导航周期摘要"] .metric-summary__number strong')).toHaveText("0.00");
  const activeUsers = await navigation.getByRole("table", { name: "全局导航使用结果", exact: true }).locator("tbody tr").first().locator("td").nth(2).innerText();
  expect(Number(activeUsers.replaceAll(",", ""))).toBeGreaterThan(0);
  await expect(navigation.locator('[aria-label="所选导航周期摘要"]')).toContainText(`同范围活跃用户数 ${activeUsers} 人`);
  await navigation.getByRole("button", { name: "演示导航 03", exact: true }).click();
  await expect(navigation.locator('[aria-label="所选导航周期摘要"]')).toContainText("部分数据");
  expect(errors).toEqual([]);
});

test("悬停显示双方实际日期，点击保留读数", async ({ page }) => {
  await page.setViewportSize({ width: 1280, height: 1000 });
  const view = { range: { start: "2026-09-02", end: "2026-09-08" }, compared: true, mixed: false, selected: ["video_home"], days: 7, dimension: "平台" };
  await page.goto(`${href}&view=${encodeURIComponent(JSON.stringify(view))}`);
  await page.getByRole("region", { name: "单功能分析范围", exact: true }).getByRole("radiogroup", { name: "展示方式", exact: true }).getByRole("radio", { name: "总体", exact: true }).click();
  const chart = page.getByRole("img", { name: "所选功能渗透率多系列趋势", exact: true });
  await chart.scrollIntoViewIfNeeded();
  const point = await chart.evaluate(async el => {
    const { getInstanceByDom } = await import("/node_modules/.vite/deps/echarts_core.js");
    const instance = getInstanceByDom(el), option = instance.getOption();
    const pixel = instance.convertToPixel({ seriesIndex: 0 }, [2, option.series[0].data[2]]), rect = el.getBoundingClientRect();
    return { x: rect.left + pixel[0], y: rect.top + pixel[1] };
  });
  await page.mouse.move(point.x, point.y);
  await page.mouse.click(point.x, point.y);
  const dialog = page.getByRole("dialog", { name: "功能趋势读数", exact: true });
  await expect(dialog).toContainText("2026-09-04"); await expect(dialog).toContainText("2026-08-28");
  await expect(dialog.getByRole("button", { name: /^关闭/ })).toHaveCount(1);
});

test("全局导航独立迁入，同源整体人数次数人均、详情、刷新与完整导出", async ({ page }) => {
  await page.setViewportSize({ width: 1280, height: 1000 });
  const view = { range: { start: "2026-09-02", end: "2026-09-08" }, compared: true, mixed: false, selected: [], days: 7, dimension: "平台" };
  await page.goto(`${href}&view=${encodeURIComponent(JSON.stringify(view))}`);
  const navigation = page.getByRole("article", { name: "全局导航", exact: true });
  const table = navigation.getByRole("table", { name: "全局导航使用结果", exact: true });
  await expect(table.locator("tbody tr")).toHaveCount(5);
  await expect(page.getByRole("table", { name: "全部功能使用结果", exact: true }).locator("tbody tr")).toHaveCount(50);
  await expect(navigation.locator(".data-origin-badge")).toHaveText("演示数据");
  const first = table.locator("tbody tr").first();
  await expect(first.getByRole("button", { name: "演示导航 01", exact: true })).toHaveClass(/ui-button--ghost/);
  const values = await first.locator("td").allTextContents();
  const numeric = value => Number(value.replaceAll(",", "").replace("%", ""));
  expect(numeric(values[3])).toBeCloseTo(numeric(values[0]) / numeric(values[2]) * 100, 2);
  expect(numeric(values[4])).toBeCloseTo(numeric(values[1]) / numeric(values[0]), 2);
  await first.getByRole("button", { name: "查看趋势", exact: true }).click();
  await navigation.getByRole("radio", { name: "使用者人均点击次数", exact: true }).click();
  await expectOverallNavigation(navigation);
  await expect(navigation.locator('[aria-label="所选导航周期摘要"] .metric-summary__number strong')).toHaveText(values[4]);
  await page.reload();
  await expect(navigation.getByRole("radio", { name: "使用者人均点击次数", exact: true })).toHaveAttribute("aria-checked", "true");
  await expect(navigation.getByRole("button", { name: "演示导航 01", exact: true })).toHaveAttribute("aria-pressed", "true");
  await expectOverallNavigation(navigation);
  const chart = navigation.getByRole("img", { name: "所选导航使用趋势", exact: true });
  await chart.scrollIntoViewIfNeeded();
  const point = await chart.evaluate(async el => {
    const { getInstanceByDom } = await import("/node_modules/.vite/deps/echarts_core.js");
    const instance = getInstanceByDom(el), option = instance.getOption(), rect = el.getBoundingClientRect();
    const pixel = instance.convertToPixel({ seriesIndex: 0 }, [2, option.series[0].data[2]]);
    return { x: rect.left + pixel[0], y: rect.top + pixel[1] };
  });
  await page.mouse.click(point.x, point.y);
  const reading = page.getByRole("dialog", { name: "导航趋势读数 · 2026-09-04", exact: true });
  await expect(reading).toContainText("2026-08-28"); await expect(reading).toContainText("点击次数"); await expect(reading).toContainText("点击用户数");
  await page.keyboard.press("Escape");
  await navigation.getByRole("button", { name: "查看同口径数据表", exact: true }).click();
  const complete = page.getByRole("dialog", { name: "导航完整逐日数据", exact: true });
  await expect(complete.getByRole("table", { name: "导航逐日计算输入" })).toBeVisible();
  await expect(complete.getByRole("table", { name: "导航逐日计算输入" }).locator("tbody tr")).toHaveCount(14);
  await expect(complete.getByRole("columnheader", { name: "公式", exact: true })).toHaveCount(0);
  await expect(complete.getByRole("columnheader", { name: /分组|客户端|新老用户/ })).toHaveCount(0);
  await expect(complete).toContainText("2026-09-08"); await expect(complete).toContainText("2026-08-26");
  await page.keyboard.press("Escape");
  await navigation.getByRole("button", { name: "导出全局导航", exact: true }).click();
  const downloading = page.waitForEvent("download");
  await page.getByRole("dialog", { name: "导出全局导航", exact: true }).getByRole("button", { name: "下载演示 XLSX", exact: true }).click();
  const raw = (await readFile(await (await downloading).path())).toString();
  expectOverallNavigationExport(raw);
  for (const text of ["2026-08-26", "使用者人均点击次数"]) expect(raw).toContain(text);
  expect(raw).not.toContain("member");
  await page.getByRole("button", { name: "导出功能使用概览", exact: true }).click();
  const wholeDownload = page.waitForEvent("download");
  await page.getByRole("dialog", { name: "导出功能使用概览", exact: true }).getByRole("button", { name: "下载演示 XLSX", exact: true }).click();
  const whole = (await readFile(await (await wholeDownload).path())).toString();
  for (const text of ["01_功能概览", "04_功能目录与状态", "05_全局导航", "06_导航逐日", "physical_goods_detail"]) expect(whole).toContain(text);
  expect(whole).not.toContain("07_导航结构");
  await selectReviewState(page, "组合异常态");
  const zero = table.locator("tbody tr").first();
  await expect(zero.locator("td").nth(3)).toHaveText("0.00%"); await expect(zero.locator("td").nth(4)).toHaveText("—");
  await expect(table).toContainText("未配置"); await expect(table).toContainText("部分数据"); await expect(table).toContainText("查询失败");
  await table.getByRole("button", { name: "重试", exact: true }).click(); await expect(table).not.toContainText("查询失败");
});

test("功能与导航三档布局、空搜索及导航不混入启动页", async ({ page }) => {
  const errors = []; page.on("pageerror", error => errors.push(error.message));
  for (const width of [1280, 1024, 390]) {
    await page.setViewportSize({ width, height: 950 });
    await page.goto(href);
    const overview = page.getByRole("article", { name: "各功能使用概览", exact: true });
    await overview.getByRole("textbox", { name: "搜索功能", exact: true }).fill("没有匹配的功能zz");
    await expect(overview.getByRole("table", { name: "全部功能使用结果" })).toContainText("没有可展示的数据");
    await overview.getByRole("textbox", { name: "搜索功能", exact: true }).fill("");
    await expect(overview.getByRole("table", { name: "全部功能使用结果" }).locator("tbody tr")).toHaveCount(50);
    await page.screenshot({ path: `/private/tmp/ypbi-function-table-${width}.png` });
    const navigation = page.getByRole("article", { name: "全局导航", exact: true });
    await navigation.getByRole("button", { name: "演示导航 01", exact: true }).click();
    await expectOverallNavigation(navigation);
    await expect(navigation.getByRole("table", { name: "全局导航使用结果", exact: true }).locator("tbody tr")).toHaveCount(5);
    await expect(navigation.getByRole("img", { name: "所选导航使用趋势", exact: true })).toBeVisible();
    await navigation.scrollIntoViewIfNeeded();
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);
    expect(await navigation.evaluate(el => el.getBoundingClientRect().right)).toBeLessThanOrEqual(width);
    expect(await navigation.getByRole("region", { name: "全局导航使用结果", exact: true }).evaluate(el => el.getBoundingClientRect().right)).toBeLessThanOrEqual(width);
    await page.screenshot({ path: `/private/tmp/ypbi-navigation-usage-${width}.png` });
  }
  await selectReviewState(page, "组合异常态");
  const navigation = page.getByRole("article", { name: "全局导航", exact: true });
  await navigation.getByRole("button", { name: "演示导航 02", exact: true }).click();
  await expect(navigation.getByRole("heading", { name: "未配置", exact: true })).toBeVisible();
  await expect(navigation.getByRole("img", { name: "所选导航使用趋势", exact: true })).toHaveCount(0);
  await page.goto(`${base}/dashboards/public?design=dashboard-center&board=5.15`);
  await expect(page.getByRole("article", { name: "全局导航", exact: true })).toHaveCount(0);
  expect(errors).toEqual([]);
});
