import { ReviewTools } from "../components/ReviewTools";
import { useEffect, useMemo, useRef, useState, type ReactElement, type ReactNode } from "react";
import { readPreviewQuery } from "./preview-query";
import { usePreviewQuery } from "./usePreviewQuery";
import { Copy, Maximize2, RefreshCw, Search, Star } from "lucide-react";
import { Chart } from "../../components/Chart";
import { Button } from "../../components/ui/Button";
import { DateRangePicker } from "../../components/ui/DateRangePicker";
import { FloatingHint } from "../../components/ui/FloatingHint";
import { ChartDataTable } from "../../components/ui/ChartDataTable";
import { PaginatedTable } from "../../components/ui/PaginatedTable";
import { PaginatedLegend } from "../../components/ui/PaginatedLegend";
import { Toast, useToast } from "../../components/ui/Toast";
import { MetricReadingDialog } from "../features/dashboards/MetricReadingDialog";
import { MetricSummary } from "../features/dashboards/MetricSummary";
import { AnalysisScopeControls, useAnalysisGroupVisibility, type AnalysisDisplayMode } from "../features/dashboards/AnalysisScopeControls";
import { GroupedTrend, type GroupedTrendPoint, type TrendGroup } from "../features/dashboards/GroupedTrend";
import { CalculationEvidence } from "../features/dashboards/CalculationEvidence";
import { DashboardHeader, DashboardPanel } from "../features/dashboards/DashboardPresentation";
import { DashboardActions, DashboardQueryFields } from "../features/dashboards/DashboardToolbar";
import { PreviewExportControl } from "../features/dashboards/PreviewExportControl";
import { StatePanel } from "../components/StatePanel";
import { BoardSelect } from "./ExtendedBoardPreview";
import { previewFavorites, setPreviewFavorite } from "./preview-favorites";
import { downloadPreviewWorkbook, type WorkbookSheet } from "./preview-workbook";

import { CHART_PALETTE } from "../../theme/tokens";
import { demoPrevious, demoRangeLabel } from "./extended-board-model";
import { DEFAULT_FUNCTION_VIEW, FUNCTION_MARKER, functionCatalog, functionHref, functionMetric, functionResult, functionRows, functionTrendRange, parseFunctionView, percentage, sortFunctionRows, type FunctionView } from "./function-preview-model";
import { GlobalNavigationUsage } from "./GlobalNavigationUsage";
import { DEFAULT_NAVIGATION_VIEW, navigationSheets, navigationSnapshot } from "./global-navigation-usage-model";
import { OVERALL_USAGE_SCOPE, USAGE_CLIENTS, USAGE_AUDIENCES, usageScopeKey, usageScopeLabel, type UsageScope } from "./usage-observation-fixtures";
import { FunctionUsageStructure, functionStructureSheet, functionTrendSheet } from "./FunctionUsageStructure";
import "./topic-previews.css";
import "./extended-board-preview.css";
import "./function-preview.css";

const FUNCTION_GROUP_CLIENTS = USAGE_CLIENTS.filter(item => item.value === "android" || item.value === "ios");
const FUNCTION_GROUP_AUDIENCES = USAGE_AUDIENCES.filter(item => item.value !== "overall");
const functionGroupId = (client: string, audience: string) => `${client}:${audience}`;

function FunctionGroupComparison({ id, name, range, trendRange, compared, zero, selection, exportAction, onOpen }: {
  id: string; name: string; range: FunctionView["range"]; trendRange: FunctionView["range"]; compared: boolean; zero: boolean;
  selection: { groups: string[]; setGroups: (values: string[]) => void };
  exportAction: ReactElement; onOpen: (title: string, content: ReactNode) => void;
}) {
  const groups: TrendGroup[] = FUNCTION_GROUP_CLIENTS.flatMap((client, clientIndex) => FUNCTION_GROUP_AUDIENCES.map((audience, audienceIndex) => ({ id: functionGroupId(client.value, audience.value), label: `${client.label} · ${audience.label}`, color: CHART_PALETTE[clientIndex * 2 + audienceIndex] })));
  const trendModels = new Map(groups.map(group => { const [client, audience] = group.id.split(":"); return [group.id, functionMetric(id, trendRange, compared, { client: client as UsageScope["client"], audience: audience as UsageScope["audience"] }, zero)]; }));
  const summaryModels = new Map(groups.map(group => { const [client, audience] = group.id.split(":"); return [group.id, functionMetric(id, range, compared, { client: client as UsageScope["client"], audience: audience as UsageScope["audience"] }, zero)]; }));
  const overall = functionMetric(id, trendRange, compared, OVERALL_USAGE_SCOPE, zero);
  const overallResult = overall.result.status === "available" ? overall.result : null;
  const count = Math.max(overallResult?.trend.current.length ?? 0, ...groups.map(group => { const result = trendModels.get(group.id)!.result; return result.status === "available" ? result.trend.current.length : 0; }));
  const points: GroupedTrendPoint[] = Array.from({ length: count }, (_, index) => {
    const overallPoint = overallResult?.trend.current[index], values: Record<string, number | null> = {}, states: Record<string, string> = {}, basis: NonNullable<GroupedTrendPoint["basis"]> = {}, previousValues: Record<string, number | null> = {}, previousBasis: NonNullable<NonNullable<GroupedTrendPoint["comparison"]>["basis"]> = {};
    groups.forEach(group => { const result = trendModels.get(group.id)!.result; const point = result.status === "available" ? result.trend.current[index] : undefined; values[group.id] = point?.value?.raw ?? null; states[group.id] = point?.stateLabel ?? (result.status === "available" ? "未产出" : result.label ?? result.status); if (point?.calculation) basis[group.id] = point.calculation; previousValues[group.id] = point?.counterpart?.raw ?? null; const previous = result.status === "available" ? result.trend.comparison?.[index] : undefined; if (previous?.calculation) previousBasis[group.id] = previous.calculation; });
    return { date: overallPoint?.actualDate ?? "—", values, states, basis, overall: overallPoint?.value?.raw ?? null, overallBasis: overallPoint?.calculation, ...(compared ? { comparison: { date: overallPoint?.counterpart?.actualDate ?? "—", values: previousValues, basis: previousBasis, overall: overallPoint?.counterpart?.raw ?? null, overallBasis: overallResult?.trend.comparison?.[index]?.calculation } } : {}) };
  });
  return <GroupedTrend title={`${name}功能渗透率`} groups={groups} points={points} kind="line" unit="%" format={percentage} queryKey={`${id}:${trendRange.start}:${trendRange.end}:${compared}:${zero}`} exportAction={exportAction} onOpen={onOpen} mode="groups" showControls={false} showLegend selection={{ selected: selection.groups, setSelected: selection.setGroups }} summary={ids => <div className="topic-preview__group-summary">{ids.map(groupId => { const group = groups.find(item => item.id === groupId)!; const result = summaryModels.get(groupId)!.result; return <section key={groupId}><span>{group.label}</span><strong>{result.status === "available" ? `${result.value.display}%` : "—"}</strong><small>{result.status === "available" ? result.completeness === "complete" ? "完整" : "部分" : result.label}</small></section>; })}</div>} />;
}

export default function FunctionUsagePreview() {
  const initial = parseFunctionView(new URLSearchParams(location.search).get("view")) ?? { ...DEFAULT_FUNCTION_VIEW, range: readPreviewQuery().range, compared: readPreviewQuery().compared };
  const initialScope = initial.structureScope ?? OVERALL_USAGE_SCOPE;
  const [view, setView] = useState(initial), [draft, setDraft] = useState(initial), [search, setSearch] = useState(""), [order, setOrder] = useState("value"), [favorite, setFavorite] = useState(() => previewFavorites().includes("5.5")), [hidden, setHidden] = useState<string[]>([]), [recovered, setRecovered] = useState<string[]>([]), [analysisMode, setAnalysisMode] = useState<AnalysisDisplayMode>(() => usageScopeKey(initialScope) === "overall:overall" ? "groups" : "overall");
  usePreviewQuery(view.range, view.compared);
  const [reading, setReading] = useState<{ title: string; content: ReactNode } | null>(null);
  const root = useRef<HTMLDivElement>(null), detail = useRef<HTMLDivElement>(null), { notice, notify } = useToast();
  const pending = draft.range.start !== view.range.start || draft.range.end !== view.range.end || draft.compared !== view.compared;
  const update = (next: FunctionView) => { setView(next); window.history.pushState(window.history.state, "", functionHref(next)); };
  useEffect(() => { const restore = () => { const next = parseFunctionView(new URLSearchParams(location.search).get("view")); if (next) { setView(next); setDraft(next); setHidden([]); setRecovered([]); setAnalysisMode(usageScopeKey(next.structureScope ?? OVERALL_USAGE_SCOPE) === "overall:overall" ? "groups" : "overall"); } }; window.addEventListener("popstate", restore); return () => window.removeEventListener("popstate", restore); }, []);
  const rows = useMemo(() => functionRows(view).map(row => recovered.includes(row.id) ? functionRows({ ...view, mixed: false }).find(item => item.id === row.id)! : row), [view, recovered]);
  const navigation = useMemo(() => navigationSnapshot(view.range, view.compared, view.mixed, recovered), [view.range.start, view.range.end, view.compared, view.mixed, recovered]);
  const sorted = sortFunctionRows(rows, order);
  const filtered = sorted.filter(row => `${row.name} ${row.id} ${row.module}`.toLowerCase().includes(search.trim().toLowerCase()));
  const scope = view.selected.length === 1 ? view.structureScope ?? OVERALL_USAGE_SCOPE : OVERALL_USAGE_SCOPE;
  const selected = view.selected.map(id => { const row = rows.find(row => row.id === id)!; return { ...row, zeroSample: row.current?.users === 0, current: row.current ? functionResult(id, view.range, scope, row.current.users === 0) : null }; }), enabled = selected.filter(row => row.status === "完整");
  const trendRange = functionTrendRange(view), trends = enabled.map(row => ({ row, model: functionMetric(row.id, trendRange, view.compared, scope, row.zeroSample) }));
  const summaryModels = new Map(enabled.map(row => [row.id, functionMetric(row.id, view.range, view.compared, scope, row.zeroSample)]));
  const colors = new Map(view.selected.map((id, i) => [id, CHART_PALETTE[i % CHART_PALETTE.length]]));
  const selectedOne = selected.length === 1 ? selected[0] : null;
  const groupVisibility = useAnalysisGroupVisibility(FUNCTION_GROUP_CLIENTS.map(item => item.value), FUNCTION_GROUP_AUDIENCES.map(item => item.value), `${selectedOne?.id ?? "none"}:${view.range.start}:${view.range.end}:${view.days}`);
  const metadata: WorkbookSheet = { name: "00_导出说明", rows: [["数据性质", "合成演示结果，非正式业务数据"], ["目录来源", functionCatalog.source], ["目录版本", functionCatalog.version], ["通用模板", functionCatalog.templateSource], ["正式指标引用", "尚未登记，未创建新的指标 ID"], ["统计日期", demoRangeLabel(view.range)], ["对比日期", view.compared ? demoRangeLabel(demoPrevious(view.range)) : "不对比"], ["所选趋势日期", demoRangeLabel(trendRange)], ["功能局部范围", usageScopeLabel(scope)], ["导出范围", "功能概览完整目录；趋势与结构按实际选择，不受搜索、分页和隐藏图例影响"], ["单位", "渗透率按 0–100 输出，人数为同范围样本，不从比例反推"]] };
  const overviewSheet: WorkbookSheet = { name: "01_功能概览", rows: [["功能", "稳定页面ID", "模块", "渗透率（%）", "使用用户数", "同范围活跃用户数", ...(view.compared ? ["对比渗透率（%）", "变化（百分点）"] : []), "状态"], ...sorted.map(row => [row.name, row.id, row.module, row.current ? row.current.rate * 100 : null, row.current?.users ?? null, row.current?.active ?? null, ...(view.compared ? [row.previous ? row.previous.rate * 100 : null, row.current && row.previous ? (row.current.rate - row.previous.rate) * 100 : null] : []), row.status])] };
  const trendSheet = functionTrendSheet(enabled, trendRange, view.compared, scope);
  const structureSheet = selectedOne?.current ? functionStructureSheet(selectedOne.id, selectedOne.name, view.range, view.compared, selectedOne.zeroSample) : null;
  const limits: WorkbookSheet = { name: "99_数据状态与限制", rows: [["正式查询", "尚未接入；定义与合成观察不能证明实际采集"], ["范围", "50项页面目录与全局导航独立；不包含用户ID或原始事件"], ["全局导航", "隔离演示Tab，非正式业务名单；M052活跃分母、查询与验数待就绪"], ["导航计算", "渗透率=点击用户÷同范围活跃用户；使用者人均=点击次数÷点击用户；零分母为空值，不平均日值"], ["真实数据门槛", "稳定模板引用、身份去重、同口径分母与查询验数逐项准入"], ["所选功能", selected.length ? selected.map(row => row.name).join("、") : "未选择；不生成趋势和结构 Sheet"], ["局部结构", selected.length === 1 ? usageScopeLabel(scope) : "单选一个功能后查看"], ...selected.filter(row => !row.current).map(row => [row.name, row.status])] };
  const exportAction = (title: string, sheets: WorkbookSheet[], iconOnly = false) => <PreviewExportControl name={title} scope="完整已应用结果；包含实际范围、同口径样本和状态。" context="本地合成演示数据" pending={pending} iconOnly={iconOnly} onDownloadPreview={() => downloadPreviewWorkbook(title, [metadata, ...sheets, limits])} />;
  const fullSheets = [overviewSheet, ...(trends.length ? [trendSheet] : []), ...(structureSheet ? [structureSheet] : []), { name: "04_功能目录与状态", rows: [["功能", "稳定页面ID", "业务模块", "定义", "登记状态", "正式查询"], ...functionCatalog.items.map(row => [row.name, row.id, row.module, row.definition, row.trackingStatus, "未接入、未验数"])] }, ...navigationSheets(navigation.periods)];
  const choose = (id: string) => { if (view.selected.includes(id)) update({ ...view, selected: view.selected.filter(value => value !== id) }); else if (view.selected.length < 5) update({ ...view, selected: [...view.selected, id] }); else notify("最多选择 5 个功能；全部功能仍保留在概览和导出中"); };
  const inspect = (id: string) => { update({ ...view, selected: [id] }); setHidden([]); setAnalysisMode("groups"); requestAnimationFrame(() => detail.current?.scrollIntoView({ block: "start" })); };
  const table = <PaginatedTable label="全部功能使用结果" tableClassName="function-preview__table" columnCount={view.compared ? 9 : 7} resetKey={[view.range.start, view.range.end, view.mixed, search, order].join("|")} head={<tr><th>趋势</th><th>功能</th><th>使用用户数</th><th>同范围活跃用户数</th><th>渗透率</th>{view.compared && <><th>对比渗透率</th><th>变化（百分点）</th></>}<th>状态</th><th>详情</th></tr>} rows={filtered.map(row => <tr key={row.id} data-function-id={row.id}><td><input type="checkbox" aria-label={`选择${row.name}趋势`} checked={view.selected.includes(row.id)} onChange={() => choose(row.id)} disabled={!row.current || (view.selected.length >= 5 && !view.selected.includes(row.id))} /></td><td><button type="button" onClick={() => inspect(row.id)}>{row.name}</button><small className="topic-preview__content-id">{row.module}</small></td><td>{row.current?.users.toLocaleString() ?? "—"}</td><td>{row.current?.active.toLocaleString() ?? "—"}</td><td><div className="function-preview__rate"><span>{percentage(row.current?.rate ?? null)}</span>{row.current && <span className="function-preview__rate-track" aria-hidden="true"><i style={{ width: `${row.current.rate * 100}%` }} /></span>}</div></td>{view.compared && <><td>{percentage(row.previous?.rate ?? null)}</td><td>{row.current && row.previous ? ((row.current.rate - row.previous.rate) * 100).toFixed(2) : "—"}</td></>}<td>{row.status}</td><td>{row.status === "查询失败" ? <button type="button" onClick={() => setRecovered(ids => [...ids, row.id])}>重试</button> : <button type="button" onClick={() => inspect(row.id)}>查看趋势</button>}</td></tr>)} />;
  const icon = (label: string, action: () => void, content: ReactNode) => <FloatingHint content={label}><button type="button" className="ui-icon-button" aria-label={label} onClick={action}>{content}</button></FloatingHint>;
  const tableTools = <div className="function-preview__table-tools"><label className="ui-search topic-preview__search"><Search /><input aria-label="搜索功能" placeholder="搜索功能、页面标识或模块" value={search} onChange={event => setSearch(event.target.value.slice(0, 120))} /></label><span>趋势已选 {view.selected.length}/5</span><Button size="sm" disabled={!view.selected.length} onClick={() => update({ ...view, selected: [] })}>清空选择</Button></div>;
  const trendReadings = (index: number) => trends.filter(item => !hidden.includes(item.row.id)).flatMap(item => {
    if (item.model.result.status !== "available") return [];
    const point = item.model.result.trend.current[index];
    if (!point) return [];
    return [{ id: item.row.id, name: item.row.name, point }];
  });
  const readTrend = (index: number) => setReading({ title: "功能趋势读数", content: <>{trendReadings(index).map(({ id, name, point }) => <section key={id}><h3>{name}</h3><dl className="v2-detail-list"><div><dt>当前期日期</dt><dd>{point.actualDate}</dd></div><div><dt>当前期渗透率</dt><dd>{point.value?.display ?? "—"}</dd></div>{point.counterpart && <><div><dt>对比期日期</dt><dd>{point.counterpart.actualDate}</dd></div><div><dt>对比期渗透率</dt><dd>{point.counterpart.display}</dd></div><div><dt>变化</dt><dd>{point.differenceDisplay}</dd></div></>}</dl>{point.calculation && <CalculationEvidence basis={point.calculation} />}</section>)}<p>{functionCatalog.template.definition}。{functionCatalog.template.rule}。</p></> });
  return <div ref={root} className="v2-page topic-preview board-preview function-preview" data-preview={FUNCTION_MARKER}>
    <ReviewTools><div className="topic-preview__notice"><span>开发环境体验 · 目录来自权威定义，结果为合成演示数据</span><div className="topic-preview__controls">{[false, true].map(mixed => <Button key={String(mixed)} variant={view.mixed === mixed ? "primary" : "secondary"} onClick={() => { update({ ...view, mixed }); setRecovered([]); }}>{mixed ? "组合异常态" : "正常态"}</Button>)}</div></div></ReviewTools>
    <DashboardHeader title="功能使用概览" breadcrumb="公共概览 / 产品体验" description="比较活跃用户使用各页面或模块的程度，查看所选功能趋势与结构，并独立分析底部导航触达与使用频次；各功能与Tab可重叠，不合计渗透率。"><div className="topic-preview__toolbar"><div className="topic-preview__query"><DashboardQueryFields date={<DateRangePicker value={draft.range} maxDate="2026-09-08" today="2026-09-10" maxDays={366} onChange={range => setDraft({ ...draft, range })} />} scope={<span className="topic-preview__scope">大盘整体</span>} comparison={<BoardSelect label="对比周期" value={draft.compared ? "previous" : "none"} onChange={value => setDraft({ ...draft, compared: value === "previous" })} values={[{ value: "previous", label: "上一等长周期" }, { value: "none", label: "不对比" }]} />} apply={<Button variant="primary" onClick={() => { update({ ...view, range: draft.range, compared: draft.compared }); setRecovered([]); notify("已应用演示条件"); }}>应用</Button>} /></div><div className="topic-preview__actions"><DashboardActions favorite={icon(favorite ? "取消收藏" : "收藏看板", () => { try { setPreviewFavorite("5.5", !favorite); setFavorite(!favorite); notify(favorite ? "已取消收藏" : "已加入我的收藏（仅本机）"); } catch { notify("本机存储不可用，收藏未保存"); } }, <Star fill={favorite ? "currentColor" : "none"} />)} copyLink={icon("复制当前视图链接", () => { const href = new URL(functionHref(view), location.origin).href; navigator.clipboard.writeText(href).then(() => notify("已复制当前视图链接")).catch(() => setReading({ title: "复制当前视图链接", content: <textarea readOnly aria-label="当前视图链接" value={href} /> })); }, <Copy />)} refresh={icon("刷新看板", () => { setRecovered([]); notify("演示快照已重新载入"); }, <RefreshCw />)} fullscreen={icon("全屏查看", () => { (document.fullscreenElement ? document.exitFullscreen() : root.current?.requestFullscreen())?.catch(() => notify("当前环境不支持全屏")); }, <Maximize2 />)} exportAction={exportAction("功能使用概览", fullSheets, true)} /></div></div></DashboardHeader>
    {pending && <p className="topic-preview__pending" role="status">条件尚未应用 · 当前结果仍对应已应用条件</p>}
    <DashboardPanel title="各功能使用概览" note={`${demoRangeLabel(view.range)} · 总体范围 · 共 ${rows.length} 个页面 · 多个功能可同时使用，不合计为 100%`} tools={<BoardSelect label="功能比较排序" value={order} onChange={setOrder} values={[{ value: "value", label: "按渗透率降序" }, { value: "module", label: "按业务模块" }, ...(view.compared ? [{ value: "change", label: "按变化降序" }] : [])]} />}>
      {tableTools}{table}
      <div className="function-preview__overview-footer">{exportAction("功能使用结果", [overviewSheet])}<span>完整目录 · 稳定页面标识保留在导出与搜索中</span></div>
    </DashboardPanel>
    <div ref={detail} className="function-preview__detail"><DashboardPanel title="所选功能详情与趋势" note={`选择 1 个查看结构，最多 5 个同图比较 · 趋势 ${demoRangeLabel(trendRange)}`} tools={<BoardSelect label="功能趋势日期" value={String(view.days)} onChange={value => update({ ...view, days: Number(value) as 7 | 30 })} values={[{ value: "7", label: "近 7 日" }, { value: "30", label: "近 30 日" }]} />}>
      <div className="function-preview__selection"><details><summary>选择趋势功能（{view.selected.length}/5）</summary><div className="function-preview__choices">{rows.map(row => <label key={row.id}><input type="checkbox" aria-label={`添加${row.name}趋势`} checked={view.selected.includes(row.id)} disabled={!row.current || (view.selected.length >= 5 && !view.selected.includes(row.id))} onChange={() => choose(row.id)} />{row.name}</label>)}</div></details></div>
      {selectedOne && <AnalysisScopeControls label="单功能分析范围" onReset={() => { update({ ...view, structureScope: OVERALL_USAGE_SCOPE }); setAnalysisMode("overall"); }} canReset={usageScopeKey(scope) !== "overall:overall"} groupDisplay={{ mode: analysisMode, onModeChange: next => { setAnalysisMode(next); update({ ...view, structureScope: OVERALL_USAGE_SCOPE }); }, clientOptions: FUNCTION_GROUP_CLIENTS, selectedClients: groupVisibility.clients, onClientsChange: groupVisibility.setClients, audienceOptions: FUNCTION_GROUP_AUDIENCES, selectedAudiences: groupVisibility.audiences, onAudiencesChange: groupVisibility.setAudiences, onRestoreAll: groupVisibility.restoreAll, canRestoreAll: !groupVisibility.isAll }} note={analysisMode === "overall" ? `当前读取：${selectedOne.name} · ${usageScopeLabel(scope)}的独立结果；上方50项主表仍为总体。` : `当前显示 ${groupVisibility.groups.length} 个客户端 × 人群分组；对比期同步显示同组。`} />}
      {!selected.length ? <StatePanel compact kind="empty" title="选择要查看的功能" description="点击功能行或打开选择器；不会自动选择前五项，全部功能概览始终保留。" /> : <>
        {selectedOne && analysisMode === "groups" ? <FunctionGroupComparison id={selectedOne.id} name={selectedOne.name} range={view.range} trendRange={trendRange} compared={view.compared} zero={selectedOne.zeroSample} selection={{ groups: groupVisibility.groups, setGroups: groupVisibility.setGroups }} exportAction={exportAction("功能趋势", [trendSheet])} onOpen={(title, content) => setReading({ title, content })} /> : <>
          <div className="function-preview__summaries">{selected.map(row => <MetricSummary key={row.id} title={<FloatingHint content={`${functionCatalog.template.definition}。${functionCatalog.template.rule}。`} pinOnClick><button type="button" className="function-preview__metric-name">{row.name}</button></FloatingHint>} context={`${demoRangeLabel(view.range)} · ${usageScopeLabel(scope)}`} value={row.current?.rate != null ? (row.current.rate * 100).toFixed(2) : "—"} unit={row.current?.rate != null ? "%" : undefined} comparison={(() => { const result = summaryModels.get(row.id)?.result; return result?.status === "available" ? result.comparison : null; })()} supplementary={(() => { const result = summaryModels.get(row.id)?.result; return result?.status === "available" ? <CalculationEvidence compact basis={result.calculation}/> : null; })()} note={row.current ? `使用用户数 ${row.current.users.toLocaleString()} 人 / 同范围活跃用户数 ${row.current.active.toLocaleString()} 人${row.current.rate === null ? " · 基数为0，渗透率不可计算" : ""}` : row.status} />)}</div>
          {selectedOne?.current?.rate === null && <StatePanel compact kind="empty" title="当前人群活跃用户基数为0" description="使用用户和活跃用户保留0；渗透率与趋势不以0补位，可在交叉表选择其他范围。"/>}
          {trends.some(item => item.model.result.status === "available") && <><Chart theme="v13" ariaLabel="所选功能渗透率多系列趋势" style={{ height: 340 }} onClick={params => readTrend((params as { dataIndex: number }).dataIndex)} option={{ animation: false, grid: { left: 60, right: 30, top: 20, bottom: 35 }, tooltip: { trigger: "axis", formatter: (params: { dataIndex: number }[]) => trendReadings(params[0]?.dataIndex ?? 0).map(({ name, point }) => `${name}<br/>当前期 ${point.actualDate} · ${point.value?.display ?? "—"}${point.counterpart ? `<br/>对比期 ${point.counterpart.actualDate} · ${point.counterpart.display}<br/>变化 ${point.differenceDisplay}` : ""}`).join("<br/><br/>") }, xAxis: { type: "category", data: (trends[0].model.result.status === "available" ? trends[0].model.result.trend.current : []).map(p => p.actualDate), axisLabel: { hideOverlap: true, formatter: (value: string) => value.slice(5) } }, yAxis: { type: "value", axisLabel: { formatter: (value: number) => `${(value * 100).toFixed(0)}%` } }, series: trends.filter(item => !hidden.includes(item.row.id)).flatMap(item => { const result = item.model.result; if (result.status !== "available") return []; return [{ name: `${item.row.name} · 当前期`, type: "line", showSymbol: view.days === 7, symbolSize:7, lineStyle:{width:2}, data: result.trend.current.map(p => p.value?.raw ?? null), itemStyle: { color: colors.get(item.row.id) } }, ...(view.compared ? [{ name: `${item.row.name} · 对比期`, type: "line", showSymbol: false, data: result.trend.current.map(p => p.counterpart?.raw ?? null), lineStyle: { type: "dashed", opacity: .65 }, itemStyle: { color: colors.get(item.row.id) } }] : [])]; }) }} /><PaginatedLegend label="所选功能图例" items={enabled.map(row => ({ id: row.id, label: row.name, color: colors.get(row.id)!, selected: !hidden.includes(row.id) }))} onToggle={id => setHidden(ids => ids.includes(id) ? ids.filter(value => value !== id) : [...ids, id])} /><p className="dashboard-table-context function-preview__context">实线：当前期；{view.compared ? `虚线：对比期 ${demoRangeLabel(demoPrevious(trendRange))}` : "未启用对比"}</p><ChartDataTable title="功能趋势同口径数据表" exportAction={exportAction("功能趋势", [trendSheet])}><PaginatedTable label="功能趋势结果" columnCount={9} head={<tr>{trendSheet.rows[0].map((cell, i) => <th key={i}>{cell}</th>)}</tr>} rows={trendSheet.rows.slice(1).map((row, i) => <tr key={i}>{row.map((cell, j) => <td key={j}>{cell ?? "—"}</td>)}</tr>)} /></ChartDataTable></>}
        </>}
      </>}
    </DashboardPanel></div>
    {selectedOne?.current && structureSheet && <FunctionUsageStructure id={selectedOne.id} name={selectedOne.name} range={view.range} compared={view.compared} zero={selectedOne.zeroSample} scope={scope} focused={analysisMode === "overall"} onScope={structureScope => { update({ ...view, structureScope }); setAnalysisMode("overall"); requestAnimationFrame(() => detail.current?.scrollIntoView({ block: "start" })); }} acquisitionOpen={view.dimension === "获客类型"} exportAction={exportAction("功能结构", [structureSheet])} />}
    <GlobalNavigationUsage snapshot={navigation} state={view.navigation ?? DEFAULT_NAVIGATION_VIEW} pending={pending} onChange={navigation => update({ ...view, navigation })} onRetry={id => setRecovered(ids => [...ids, id])} onOpen={(title, content) => setReading({ title, content })} />
    {reading && <MetricReadingDialog {...reading} onClose={() => setReading(null)} />}{notice && <Toast notice={notice} onClose={() => notify(null)} />}
  </div>;
}
